name: Deploy vitepress

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'docs/**'

# Skip job run if newer commit exists
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy vitepress docs
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 7
                  run_install: false

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Build
              run: pnpm docs:build --base /${{ github.event.repository.name }}/

            - name: Deploy to GH Pages 🚀
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/.vitepress/dist
